version: '3.9'
services:
  app:
    build:
      args:
        user: lims
        uid: 1000
      context: .
      dockerfile: Dockerfile-l57-p71
    container_name: lims-app
    image: lims
    volumes:
      - ../lims:/var/www/
    networks:
      - lims_network
  db:
    image: mysql:5.7
    container_name: lims-mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ${HOME}/mysql_data:/var/lib/mysql
    ports:
      - 33065:3306
    environment:
      MYSQL_ROOT_PASSWORD: rahasia
    networks:
      - lims_network
  redis:
    image: redis:7.0-alpine
    container_name: lims-redis
    ports:
      - 6379:6379
    networks:
      - lims_network
  nginx:
    image: nginx:alpine
    container_name: lims-nginx
    ports:
      - 80:80
    volumes:
      - ../lims:/var/www/
      - ./lims.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lims_network

networks:
  lims_network:
    driver: bridge
